version: '3.9'

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio-network
    command: server /data

networks:
  minio-network:
    driver: bridge